config/routes.rb
Rails.application.routes.draw do
  resources :stats, only: :index
  resources :urls, param: :slug, path: '', only: %i[new create show] do
    get 'stats', on: :member
  end

  root to: 'urls#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  AVAILABLE_TYPES = %w[url_entered].freeze

  validates :event_type, presence: true, inclusion: AVAILABLE_TYPES

  attribute :user_data, :json, default: {}

  belongs_to :url
end

app/models/url.rb
class Url < ApplicationRecord
  validates :original_url, presence: true,
                           url: { no_local: true }
  validates :slug,         presence: true,
                           uniqueness: true,
                           format: { with: /\A[a-zA-Z._-]+\z/ }
  has_many :events

  def enters_count
    events.where(event_type: :url_entered).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
    respond_to do |format|
      format.csv do
        result = GetUrlCsvStats.call
        send_data result.stats, filename: result.file_name
      end
    end
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
    @url = Url.new
  end

  def create
    result = AddUrl.call(url_params)
    if result.success?
      redirect_to stats_url_url(result.url.slug), notice: result.message
    else
      @url = result.url
      flash.alert = result.message
      render :new
    end
  end

  def show
    result = ShowUrl.call(show_params)
    if result.success?
      redirect_to result.url.original_url
    else
      redirect_to new_url_path, alert: result.message
    end
  end

  def stats
    result = GetSingleUrlStats.call(slug_params)
    if result.success?
      @url = result.url
      @stats = result.stats
    else
      redirect_to new_url_path, alert: result.message
    end
  end

  private

  def url_params
    params.require(:url).permit(:original_url, :slug)
  end

  def slug_params
    params.permit(:slug)
  end

  def show_params
    slug_params.merge ip: request.remote_ip
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<% if flash.any? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      toastr.<%= type %>('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

  <head>
    <title>Url Shortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <div class="container">
        <div class="vertical-center-row">
          <div align="center">
            <%= yield %>
            <%= render 'layouts/flash_messages' %>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/urls/new.html.erb
<%= bootstrap_form_for(@url) do |f| %>
  <%= f.url_field :original_url, placeholder: 'Type URL...', hide_label: true %>
  <%= f.text_field :slug, placeholder: 'Type your slug here or leave blank to get a random one...',
                          hide_label: true, required: false %>
  <%= f.primary 'Add' %>
<% end %>

app/views/urls/stats.html.erb
<div>
  <h2>
    <%= link_to @url.slug, url_path(@url.slug), data: { turbolinks: false } %> stats
  </h2>
</div>
<hr>
<div>
  <%= "URL added #{time_ago_in_words @url.created_at} ago" %>
</div>
<div>
  <%= "Visited #{pluralize @stats[:enters_count], 'time'}" %>
</div>